name: NuGet Publish

on:
  push:
    branches:
      - main

jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
          useConfigFile: false
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: 8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build src/saison/Saison.csproj -c Release --no-restore
      - name: Publish Saison
        run: |
          mkdir out
          dotnet pack src/saison/Saison.csproj -c Release -o out --no-restore -p:PackageVersion=${{ env.majorMinorPatch }}
          dotnet nuget push "./out/*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_TOKEN}}
          rm -rf out